---
language: ruby
script: rake spec
notifications:
  email: false
gemfile:
  - gemfiles/gemfile.ci
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
env:
  - BUILD_PUPPET_VER=2.7.14 BUILD_FACTER_VER=1.6.9
  - BUILD_PUPPET_VER=2.7.6 BUILD_FACTER_VER=1.6.9
  - BUILD_PUPPET_VER=2.6.9 BUILD_FACTER_VER=1.6.9
matrix:
  exclude:
    - rvm: 1.9.2
      gemfile: gemfiles/gemfile.ci
      env: BUILD_PUPPET_VER=2.6.9 BUILD_FACTER_VER=1.6.9
    - rvm: 1.9.3
      gemfile: gemfiles/gemfile.ci
      env: BUILD_PUPPET_VER=2.6.9 BUILD_FACTER_VER=1.6.9
